from typing import Literal, Union

AnyLiteral = Literal["any"]
IPProtocol = (
    Literal[
        "dccp",
        "ddp",
        "egp",
        "encap",
        "etherip",
        "ggp",
        "gre",
        "hmp",
        "icmp",
        "icmpv6",
        "idpr-cmtp",
        "igmp",
        "ipencap",
        "ipip",
        "ipsec-ah",
        "ipsec-esp",
        "ipv6-encap",
        "ipv6-frag",
        "ipv6-nonxt",
        "ipv6-opts",
        "ipv6-route",
        "iso-tp4",
        "l2tp",
        "ospf",
        "pim",
        "pup",
        "rdp",
        "rspf",
        "rsvp",
        "sctp",
        "st",
        "tcp",
        "udp",
        "udp-lite",
        "vmtp",
        "vrrp",
        "xns-idp",
        "xtp",
    ],
)

MACProtocol = Literal[
    "802.2",
    "arp",
    "ip",
    "ipx",
    "loop-protect",
    "mpls-unicast",
    "packing-simple",
    "pppoe-discovery",
    "service-vlan",
    "any",
    "homeplug-av",
    "ipv6",
    "lldp",
    "mpls-multicast",
    "packing-compr",
    "pppoe",
    "rarp",
    "vlan",
]
