from typing import Literal, Union

AnyLiteral = Literal["any"]
IPProtocol = Union[
    AnyLiteral,
    Literal["dccp"],
    Literal["ddp"],
    Literal["egp"],
    Literal["encap"],
    Literal["etherip"],
    Literal["ggp"],
    Literal["gre"],
    Literal["hmp"],
    Literal["icmp"],
    Literal["icmpv6"],
    Literal["idpr-cmtp"],
    Literal["igmp"],
    Literal["ipencap"],
    Literal["ipip"],
    Literal["ipsec-ah"],
    Literal["ipsec-esp"],
    Literal["ipv6-encap"],
    Literal["ipv6-frag"],
    Literal["ipv6-nonxt"],
    Literal["ipv6-opts"],
    Literal["ipv6-route"],
    Literal["iso-tp4"],
    Literal["l2tp"],
    Literal["ospf"],
    Literal["pim"],
    Literal["pup"],
    Literal["rdp"],
    Literal["rspf"],
    Literal["rsvp"],
    Literal["sctp"],
    Literal["st"],
    Literal["tcp"],
    Literal["udp"],
    Literal["udp-lite"],
    Literal["vmtp"],
    Literal["vrrp"],
    Literal["xns-idp"],
    Literal["xtp"],
]
